
create database eHonk;

use eHonk;

CREATE USER eHonkUser IDENTIFIED BY 'eHonkUser123';

GRANT usage ON *.* TO eHonkUser@localhost IDENTIFIED BY 'eHonkUser123';
grant SELECT, INSERT, UPDATE, DELETE on eHonk.* to eHonkUser@localhost;

CREATE TABLE DRIVER_REGISTER (ID INT NOT NULL AUTO_INCREMENT,
  LICENSE_PLATE VARCHAR(32) NOT NULL,
  COLOR INT,
  PHONE_NUMBER VARCHAR(16),
  REGISTER_ID VARCHAR(512) UNIQUE NOT NULL,
  TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(ID),
  INDEX(LICENSE_PLATE));
